DROP TRIGGER IF EXISTS trg_check_part_request_status ON part_requests;
DROP FUNCTION IF EXISTS fn_check_part_request_status();
DROP TRIGGER IF EXISTS trg_check_employee_manager_cycle ON employees;
DROP FUNCTION IF EXISTS fn_check_employee_manager_cycle();
DROP TRIGGER IF EXISTS trg_repair_vehicle_status_upd ON repairs;
DROP TRIGGER IF EXISTS trg_repair_vehicle_status_ins ON repairs;
DROP FUNCTION IF EXISTS fn_repair_vehicle_status();
DROP TRIGGER IF EXISTS trg_validate_transport_log ON transport_logs;
DROP FUNCTION IF EXISTS fn_validate_transport_log();
DROP TRIGGER IF EXISTS trg_check_driver_vehicle_overlap ON driver_vehicle_assignments;
DROP FUNCTION IF EXISTS fn_check_driver_vehicle_overlap();
DROP TRIGGER IF EXISTS trg_check_route_assignment_overlap ON route_assignments;
DROP FUNCTION IF EXISTS fn_check_route_assignment_overlap();
DROP TRIGGER IF EXISTS trg_refresh_repair_total_cost_from_part ON replaced_parts;
DROP TRIGGER IF EXISTS trg_refresh_repair_total_cost_from_work ON repair_works;
DROP FUNCTION IF EXISTS fn_repair_total_cost_trigger();
DROP FUNCTION IF EXISTS fn_refresh_repair_total_cost(BIGINT);
DROP TRIGGER IF EXISTS trg_set_replaced_part_total_cost ON replaced_parts;
DROP FUNCTION IF EXISTS fn_set_replaced_part_total_cost();
