TRUNCATE TABLE
    part_request_items,
    part_requests,
    replaced_parts,
    parts,
    repair_works,
    repairs,
    transport_logs,
    driver_vehicle_assignments,
    route_assignments,
    routes,
    aux_vehicles,
    trucks,
    taxis,
    route_taxis,
    buses,
    vehicles,
    repairmen,
    drivers,
    employees,
    brigades,
    vehicle_categories,
    garage_facilities,
    positions
RESTART IDENTITY CASCADE;
